### PR TITLE
added Bitcore BTX

### PR DESCRIPTION
**Pull request by dArkjON**
Adding BitCore (BTX)

Website: bitcore.cc
SLIP44=160
COIN_P2PKH_VERSION=3
COIN_P2SH_VERSION=125

### CODE REVIEW

**Comment by dArkjON** [comment]
New Pull to #50 as authorized user.

**Comment by keepkeyjon** [comment]
@dArkjON what do you mean by "authorized user"?

**Comment by dArkjON** [comment]
> @dArkjON what do you mean by "authorized user"?

I just realized that my old Pull Request was blocked auto from Github because i used the website to start the pull request and not my github client it was marked and blocked as not authorized user.

This pull should work fine now, and i hope all is working nice.

**Comment by keepkeyjon** [comment]
Rebased here: https://github.com/keepkey/keepkey-firmware/pull/60

**Pull request closed without merging**
