### PR TITLE
Rel v6.7.0

### PR DESCRIPTION
**Pull request by markrypto**

### CODE REVIEW

**Review by mcchadwick — APPROVED** [review]

**Review by mvpratt — APPROVED** [review]
approved with comments

**Comment by mvpratt** [comment]
why does this PR show commit history back to 2019, from previous releases, in the diff?

**Comment by mvpratt** [comment]
@reidrankin can you elaborate?  I don't see any key derivation changes in this PR

**Comment by reidrankin** [comment]
> @reidrankin can you elaborate?  I don't see any key derivation changes in this PR

That comment was on commit cc378f2, which reduces PIN KDF iterations by a factor of 10,000.

**Comment by reidrankin** [comment]
To clarify, the changes were reverted in 430b404. That's also a prt of this PR so it's a wash; I'm just interested in the history behind those two changes. I'm confused because 430b404 says the reversion was for testing purposes -- whereas it would seem more likely to me that the initial reduction was for testing. (And besides, I'd expect you'd want to ease testing by reducing the values of the debug build defines, but not the normal ones!)

**Pull request merged**
