### PR TITLE
Add BitcoinSV

### PR DESCRIPTION
**Pull request by keepkeyjon**
See #75

### CODE REVIEW

**Comment by kyuupichan** [comment]
We (and no one I know of) will use 0xec for derivation paths, sorry.

**Comment by keepkeyjon** [comment]
@kyuupichan do you happen to know the timeline for implementing replay protection on BSV or BCH?

**Comment by kyuupichan** [comment]
I don't think it will be implemented.

**Comment by kyuupichan** [comment]
@keepkeyjon After discussions with fellow devs, let's go with this.

However you have made several changes that seem wrong. Please copy the line for BCH and change only 2 fields: BCH to BSV, and the account path. You've changed several others without explanation (such as message signing) which will be incompatible with everyone else.

**Comment by kyuupichan** [comment]
4fef2af looks good to me.  Is there a way for me to get firmware built with that, then I can test fully?

**Comment by keepkeyjon** [comment]
@kyuupichan you'd need a device that hasn't run [v5.1.0](https://github.com/keepkey/keepkey-firmware/releases/tag/v5.1.0) or later signed firmware, or to run the emulator and use DebugLink messages to make button presses happen.

**Comment by kyuupichan** [comment]
Sounds unlikely, lol

**Comment by kyuupichan** [comment]
Thanks.  Can we expect a firmware and lbrary release soon?

**Comment by keepkeyjon** [comment]
Not immediately, but I'll ping you when we do.

**Pull request merged**
