### PR TITLE
Add SYS to definition

### PR DESCRIPTION
**Pull request by sidhujag**
Create [Syscoin](https:\\syscoin.org) definition.

HWI: https://github.com/syscoin/hwi
Slip-0044: https://github.com/satoshilabs/slips/blob/master/slip-0044.md
Slip-132: https://github.com/satoshilabs/slips/blob/master/slip-0132.md

SYS BIP32 path is m/84' or 44' or 49'/57'/0/0

We use BIP84 in our apps/wallets and segwit by default.

### CODE REVIEW

**Comment by greatwolf** [comment]
What's the current status of this PR?

**Comment by sidhujag** [comment]
> What's the current status of this PR?

It was waiting for the merge but looks like theres conflicts, shall I resolve and you merge after that?

**Comment by greatwolf** [comment]
I don't have commit access. I was inquiring about it since I wanted to add support for syscoin into KeepKey client which of course needs this PR merged in to work.

**Comment by sidhujag** [comment]
> I don't have commit access. I was inquiring about it since I wanted to add support for syscoin into KeepKey client which of course needs this PR merged in to work.

I would ping keepkey and ask for the support

**Comment by greatwolf** [comment]
@sidhujag  I've submitted the issue on their normal support channels. Will see what happens. In the mean time can you update this PR so the conflict is resolved and ready to be merged in? There's been some slight change in coins.def since this PR but fixing it looks straightforward enough.

**Comment by markrypt0** [comment]
Closed, incomplete PR

**Pull request closed without merging**
